/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Dictionary',
      link: {
        type: 'generated-index',
        slug: 'category/dictionary',
        description: 'A dictionary for various terms and knowledge.',
      },
      collapsed: true,
      items: [
        'dictionary/zones',
        'dictionary/items',
        'dictionary/chibi-animations',
        'dictionary/chibi-emotions',
        'dictionary/system-flags',
      ],
    },
    {
      type: 'category',
      label: 'Scripting',
      link: {
        type: 'generated-index',
        slug: 'category/scripting',
        description: 'Everything about ev_scripts.',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Setting up',
          link: {
            type: 'generated-index',
            slug: 'category/scripting/setup',
            description: 'Setup instructions and guides on editing in-game ev_scripts. This is all done in RomFS.',
          },
          collapsed: true,
          items: [
            'scripting/setup/ev-as',
            'scripting/setup/placedatas',
            'scripting/setup/scripting-guide',
          ],
        },
        {
          type: 'doc',
          label: 'Scripting Introduction',
          id: 'scripting/introduction'
        },
        {
          type: 'doc',
          label: 'PlaceData',
          id: 'scripting/place-data'
        },
        {
          type: 'doc',
          label: 'StopData',
          id: 'scripting/stop-data'
        },
        {
          type: 'category',
          label: 'Commands',
          link: {
            type: 'generated-index',
            title: 'Commands',
            description: 'This is a list of the most commonly used commands in BDSP. Commands are used in functions in the game.'
          },
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Scripting logic',
              link: {
                type: 'generated-index',
                title: 'Scripting logic',
                description: 'This is a list of scripting logic related commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/logic'
                },
              ],
            },
            {
              type: 'category',
              label: 'Interface',
              link: {
                type: 'generated-index',
                title: 'Interface',
                description: 'This is a list of interface related commands. They are used to displaying various elements to the player and initiating animation commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/interface'
                },
              ],
            },
            {
              type: 'category',
              label: 'Game data',
              link: {
                type: 'generated-index',
                title: 'Game data',
                description: 'This is a list of game data related commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/gamedata'
                },
              ],
            },
            {
              type: 'category',
              label: 'Battle',
              link: {
                type: 'generated-index',
                title: 'Battle commands',
                description: 'This is a list of battle related commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/battle'
                },
              ],
            },
            {
              type: 'category',
              label: 'Dialogue',
              link: {
                type: 'generated-index',
                title: 'Dialogue commands',
                description: 'This is a list of commands related to dialogue.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/dialogue'
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Animation commands',
          link: {
            type: 'generated-index',
            title: 'Animation commands',
            description: 'This is a list of the most commonly used animation commands in BDSP. Animation commands are used in functions in the game for showing cutscenes and more.'
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'scripting/animation-commands'
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'ExeFS Editing',
      link: {
        type: 'generated-index',
        slug: 'category/exefs',
        description: 'Modifying the underlaying game code, or Executable File System (ExeFS).',
      },
      collapsed: true,
      items: [
        'exefs/guide',
        'exefs/ghidra',
        'exefs/exlaunch',
        'exefs/headers',
        'exefs/hooks',
        'exefs/logging',
        'exefs/debugging',
      ],
    },
    {
      type: 'category',
      label: 'Unity',
      link: {
        type: 'generated-index',
        slug: 'category/lumitool-guides',
        description: 'Create assets in Unity and use LumiTool to allow the game to use them.',
      },
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'LumiTool Introduction',
          id: 'lumitool-guides/introduction'
        },
        {
          type: 'category',
          label: 'Characters',
          link: {
            type: 'generated-index',
            title: 'Characters',
            description: 'Guides for making custom characters.'
          },
          collapsed: true,
          items: [
            'lumitool-guides/characters/setup',
            'lumitool-guides/characters/ripping',
            'lumitool-guides/characters/field-npc',
            'lumitool-guides/characters/field-player',
            'lumitool-guides/characters/battle-npc',
            'lumitool-guides/characters/battle-player',
          ],
        },
        {
          type: 'category',
          label: 'Character Shaders',
          link: {
            type: 'generated-index',
            title: 'Character Shaders',
            description: 'Shaders determine how a material is rendered on an object. There are two Character shaders that we will go over however it is technically possible to use any of the game’s other shaders. Be warned that you may run into oddities though.'
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'lumitool-guides/characters/shaders'
            },
          ],
        },
        {
          type: 'category',
          label: 'Character Monobehaviours and Components',
          link: {
            type: 'generated-index',
            title: 'Character Monobehaviours and Components',
            description: 'Monobehaviours are components that tell an object how it should behave. There are Monobehaviours that tell an object what type of entity it is as well as if it’s animated, if it has particles and a whole host of other things. In this guide I’m just going to go over the ones natively found on characters. But feel free to experiment with adding others, you can do so by clicking on your prefab and pressing the Add Component button.'
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'lumitool-guides/characters/monobehaviours'
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Editing music and sound files.',
      link: {
        type: 'generated-index',
        slug: 'category/audio',
        description: 'Editing music and sound files.',
      },
      collapsed: true,
      items: [
        'audio/labels',
      ],
    },
    {
      type: 'category',
      label: 'Documentation',
      link: {
        type: 'generated-index',
        slug: 'category/documentation',
        description: 'Guides for editing textures models and animations.',
      },
      collapsed: true,
      items: [
        'documentation/map-info-locations',
      ],
    },
  ],
};

module.exports = sidebars;
