/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Dictionary',
      link: {
        type: 'generated-index',
        slug: 'category/dictionary',
        description: 'A dictionary for various terms and knowledge.',
      },
      collapsed: true,
      items: [
        'dictionary/zones',
        'dictionary/items',
        'dictionary/chibi-animations',
        'dictionary/chibi-emotions',
      ],
    },
    {
      type: 'category',
      label: 'Scripting',
      link: {
        type: 'generated-index',
        slug: 'category/scripting',
        description: 'Everything about ev_scripts.',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Setting up',
          link: {
            type: 'generated-index',
            slug: 'category/scripting/setup',
            description: 'Setup instructions and guides on editing in-game ev_scripts. This is all done in RomFS.',
          },
          collapsed: true,
          items: [
            'scripting/setup/ev-as',
            'scripting/setup/placedatas',
            'scripting/setup/scripting-guide',
          ],
        },
        {
          type: 'doc',
          label: 'Scripting Introduction',
          id: 'scripting/introduction'
        },
        {
          type: 'doc',
          label: 'PlaceData',
          id: 'scripting/place-data'
        },
        {
          type: 'doc',
          label: 'StopData',
          id: 'scripting/stop-data'
        },
        {
          type: 'category',
          label: 'Commands',
          link: {
            type: 'generated-index',
            title: 'Commands',
            description: 'This is a list of the most commonly used commands in BDSP. Commands are used in functions in the game.'
          },
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Scripting logic',
              link: {
                type: 'generated-index',
                title: 'Scripting logic',
                description: 'This is a list of scripting logic related commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/logic'
                },
              ],
            },
            {
              type: 'category',
              label: 'Interface',
              link: {
                type: 'generated-index',
                title: 'Interface',
                description: 'This is a list of interface related commands. They are used to displaying various elements to the player and initiating animation commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/interface'
                },
              ],
            },
            {
              type: 'category',
              label: 'Game data',
              link: {
                type: 'generated-index',
                title: 'Game data',
                description: 'This is a list of game data related commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/gamedata'
                },
              ],
            },
            {
              type: 'category',
              label: 'Battle',
              link: {
                type: 'generated-index',
                title: 'Battle commands',
                description: 'This is a list of battle related commands.'
              },
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'scripting/commands/battle'
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Animation commands',
          link: {
            type: 'generated-index',
            title: 'Animation commands',
            description: 'This is a list of the most commonly used animation commands in BDSP. Animation commands are used in functions in the game for showing cutscenes and more.'
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'scripting/animation-commands'
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'ExeFS Editing',
      link: {
        type: 'generated-index',
        slug: 'category/exefs',
        description: 'Modifying the underlaying game code, or Executable File System (ExeFS).',
      },
      collapsed: true,
      items: [
        'exefs/guide',
        'exefs/ghidra',
        'exefs/exlaunch',
        'exefs/headers',
        'exefs/hooks',
        'exefs/logging',
        'exefs/debugging',
      ],
    },
    {
      type: 'category',
      label: 'Art',
      link: {
        type: 'generated-index',
        slug: 'category/art',
        description: 'Guides for editing textures models and animations.',
      },
      collapsed: true,
      items: [
        'art/animations',
        'art/mesh_and_texture_replacement',
      ],
    },
    {
      type: 'category',
      label: 'Editing music and sound files.',
      link: {
        type: 'generated-index',
        slug: 'category/audio',
        description: 'Editing music and sound files.',
      },
      collapsed: true,
      items: [
        'audio/labels',
      ],
    },
    {
      type: 'category',
      label: 'Documentation',
      link: {
        type: 'generated-index',
        slug: 'category/documentation',
        description: 'Guides for editing textures models and animations.',
      },
      collapsed: true,
      items: [
        'documentation/map-info-locations',
      ],
    },
  ]
};

module.exports = sidebars;
