const statusEffects = { // Maps to the sickID in WazaTable
  0 : "None",
  1 : "Paralysis",
  2 : "Sleep",
  3 : "Freeze",
  4 : "Burn",
  5 : "Poison",
  6 : "Confusion",
  7 : "Infatuation",
  8 : "Bound",
  9 : "Nightmare",
  10 : "Curse",
  11 : "Taunt",
  12 : "Torment",
  13 : "Disable",
  14 : "Yawn",
  15 : "Heal Block",
  16 : "Gastro Acid",
  17 : "Identified",
  18 : "Leech Seed",
  19 : "Embargo",
  20 : "Perish Song",
  21 : "Rooted",
  22 : "Block",
  23 : "Encore",
  24 : "Throat Chop",
  25 : "Roost",
  26 : "WAZALOCK",
  27 : "TAMELOCK",
  28 : "KODAWARI",
  29 : "MUSTHIT",
  30 : "MUSTHIT_TARGET",
  31 : "FLYING",
  32 : "FLYING_CANCEL",
  33 : "Telekinesis",
  34 : "Sky Drop",
  35 : "HITRATIO_UP",
  36 : "Aqua Ring",
  37 : "FORCE_WAZATYPE",
  38 : "Powder",
  39 : "Uproar",
  40 : "Thrash",
  41 : "Laser Focus",
  42 : "Tar Shot",
  43 : "Octolock",
  44 : "Jaw Lock",
  65535 : "Special",
};

module.exports = {
  statusEffects,
}