const START_OF_LINE_FORMS = {
  "hisuian": "hisui",
  "galarian": "galar",
  "alolan": "alola",
  "paldean": "paldea",
  "gigantamax": "gmax",
  "ash-": "ash ",
  "-f": "-female",
  "drive ": "",
  "type ": " ",
  " sweet": "",
  " forme power construct": " power construct",
  " rider": "",
  " wings": "",
  " mane ": " ",
  " color": "",
  "! form": "emark",
  "? form": "qmark",
}

const END_OF_LINE_FORMS = {
  "forme": "",
  "form": "",
  "pattern": "",
  "mode": "",
  "flower": "",
  "trim": "",
  "size": "",
  "style": "",
  "core": "",
  "face": "",
  "construct": "",
  "sword": "",
  "shield": "",
}

const REVERSE_ORDER_ARRAY = [
  "hisui",
  "galar",
  "alola",
  "paldea",
  "mega",
  "gmax",
  "totem",
  "eternamax",
  "dada",
  "ice",
  "white",
  "black",
  "ultra",
  "ash",
  "titanic",
  "shadow",
  "dawn",
  "dusk",
  "original",
]

module.exports = { START_OF_LINE_FORMS, END_OF_LINE_FORMS, REVERSE_ORDER_ARRAY }